name: "➕ Feature PR"
description: Create a feature PR.
title: "feat(<system>): <short-description>"
labels: [
  "feature",
  "waiting for approval"
]

body:
  - type: markdown
    attributes:
      value: |
        do not change the title field as it will be automatically formatted!.

  - type: markdown
    attributes:
      value: |
        Please fill out all required fields. Pull requests with insufficient detail may be closed.

  - type: dropdown
    id: system
    attributes:
      label: System or Component
      description: What part of the modem library does this PR affect?
      options:
        - socket
        - mqtt
        - coap
        - bluecherry
        - http
        - parser
        - modem
        - other
    validations:
      required: true

  - type: textarea
    id: short-description
    attributes:
      label: "Short Description"
      description: Please enter an explicit short description of the new feature
      placeholder: Short and explicit description of the new feature
  
  - type: input
    id: issue
    attributes:
      label: "Related Issue"
      description: "Link or number of the related issue (e.g.,Closes #123)"
      placeholder: "Closes #123"
    validations:
      required: true