name: "Label and Title by System on PR"

on:
  pull_request:
    types: [opened, edited]

permissions:
  pull_requests: write

jobs:
  process-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Label PR and set title
        uses: actions/github-script@v7
        with:
          script: |
            const systemLabels = [
              'socket',
              'mqtt',
              'coap',
              'bluecherry',
              'http',
              'parser',
              'modem',
              'other'
            ];

            const body = context.payload.pull_request.body || "";

            function extractSection(title) {
              const regex = new RegExp(`###\\s+${title}\\s+\\n+([^#]+)`, 'i');
              const match = body.match(regex);
              return match ? match[1].trim().toLowerCase() : null;
            }

            const system = extractSection("System or Component") || "other";
            const shortDesc = extractSection("Short Description") || "unspecified";

            // Determine type from labels (feat or fix)
            const labels = context.payload.pull_request.labels.map(label => label.name.toLowerCase());
            let type = "feat"; // default type

            if (labels.includes("fix")) {
              type = "fix";
            } else if (labels.includes("feat")) {
              type = "feat";
            }

            // Add system label if missing
            if (systemLabels.includes(system) && !labels.includes(system)) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: [system]
              });
            }

            // Set formatted title
            const newTitle = `${type}(${system}): ${shortDesc}`;
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              title: newTitle
            });
