name: Label and Title by System
on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  process-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Label issue and set title
        uses: actions/github-script@v7
        with:
          script: |
            const systemLabels = [
              'socket',
              'mqtt',
              'coap',
              'bluecherry',
              'http',
              'parser',
              'modem',
              'other'
            ];

            const body = context.payload.issue.body;
            const lines = body.split('\n');

            let system = 'other';
            let description = 'unspecified';

            for (let i = 0; i < lines.length; i++) {
              const line = lines[i].toLowerCase();

              if (line.includes('system or component')) {
                system = lines[i + 1].trim().toLowerCase();
              }

              if (line.includes('short description')) {
                description = lines[i + 1].trim();
              }
            }

            // ✅ Add label if it's a known system label
            if (systemLabels.includes(system)) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: [system]
              });
            }

            // ✅ Update issue title
            const newTitle = `bug(${system}): ${description}`;
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              title: newTitle
            });
